image: kdvalin/cpp-ci-container:latest

stages:
        - core
        - polymost

core:
    stage: core
    script:
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/polysoft1/polychat/core.git
        - cd core
        - export cpprestsdk_DIR="/usr/lib/x86_64-linux-gnu/cmake/" && cmake -DINCLUDE_CPPRESTSDK=ON -DINCLUDE_LIBZIP=ON .
        - make
    artifacts:
           paths:
            - core/target
            - core/src/*.h
            - core/src/commands/*.h
            - core/src/Curses/*.h
            - core/include/*.h
polymost:
        stage: polymost
        script:
                - cmake -DPOLYCHAT:STRING="$PWD/core" . && make
